name: Autograding Tests
'on':
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_session8
      id: test_session8
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 250
        setup-command: pip install pytest faker